### ISSUE TITLE
This isnt an issue but would it be possible to make one for the psp version?

### ISSUE THREAD

**Issue by MajorasMaks** [Truthkey/Birth-by-Sleep-Randomizer#1]

**Comment by Truthkey** [comment]
The problem here is the PSP can't handle most boss combinations or just having certain bosses appear in places they aren't supposed to be.
For example, the PC version can easily handle having 5 big bosses, while the PSP version usually will crash with only two and sometimes just one is enough for it to crash. Same goes for regular enemies.
